= エネルギー消費性能の算定⽅法に基づく計算ファイル用JSON定義書
{docdatetime}
:doctype: article
:toc: left
:toc-title: 目次
:pagenums:
:sectnums:
:figurenums:
:figure-caption: 図
:table-caption: 表
:note-caption: メモ
:warning-caption: 注意

== はじめに

計算過程の確認及び調査研究等に活⽤することを⽬的として公開されている、エネルギー消費性能の算定⽅法に基づく計算ファイル（https://github.com/jjj-design/pyhees）を実行するための住宅全体を表すJSONの定義を示します。

== ルートオブジェクト

=== 概要

住戸全体を表すルートオブジェクトです。次の表のキーから構成されます。

[width="100%",cols="30%, 20%, 50%",options="header",]
|===
|キー |型 |意味
|region |数値 |地域の区分
|type |文字列 |住宅タイプ
|tatekata |文字列 |住宅の建て方
|n_p |文字列 |居住人数 (自立拡張)
|A_A |数値 |床面積の合計
|A_MR |数値 |主たる居室の床面積
|A_OR |数値 |その他の居室の床面積
|reference |<<基準値計算年度オブジェクト>> |基準値計算年度を表すオブジェクト
|ENV |<<外皮オブジェクト>> |外皮性能を表すオブジェクト
|NV_MR |数値 |主たる居室の自然風の利用
|NV_OR |数値 |その他の居室の自然風の利用
|TS |真偽値 |蓄熱の利用
|r_A_ufvnt |数値 |外気が経由する床下の面積の割合
|underfloor_insulation |真偽値 |床下空間の断熱
|mode_H |文字列 |暖房方式
|H_A |<<住戸全体の暖房設備オブジェクト>> |住戸全体の暖房設備機器を表すオブジェクト
|H_MR |<<主たる居室の暖房設備オブジェクト>> |主たる居室の暖房設備機器または放熱器を表すオブジェクト
|H_OR |<<その他の居室の暖房設備オブジェクト>> |その他の居室の暖房設備機器または放熱器を表すオブジェクト
|H_HS |<<温水暖房機オブジェクト>> |温水暖房機を表すオブジェクト
|mode_C |文字列 |冷房方式
|C_A |<<住戸全体の冷房設備オブジェクト>> |住戸全体の冷房設備機器を表すオブジェクト
|C_MR |<<主たる居室の冷房設備オブジェクト>> |主たる居室の冷房設備機器を表すオブジェクト
|C_OR  |<<その他の居室の冷房設備オブジェクト>> |その他の居室の冷房設備機器を表すオブジェクト
|HW |<<給湯設備オブジェクト>> |給湯設備を表すオブジェクト
|V  |<<換気設備オブジェクト>> |換気設備を表すオブジェクト
|HEX |<<熱交換型換気設備オブジェクト>> |熱交換型換気設備を表すオブジェクト
|L |<<照明設備オブジェクト>> |照明設備を表すオブジェクト
|SHC |<<太陽熱利用オブジェクト>> |太陽熱利用を表すオブジェクト
|PV |<<太陽光発電設備の配列>> |太陽光発電設備を表す配列
|CG |<<コージェネレーション設備オブジェクト>> |コージェネレーション設備を表すオブジェクト
|AP |<<家電設備オブジェクト>> |家電設備を表すオブジェクト(自立拡張)
|===

=== キー

==== regionキー

地域の区分は次の表の値を指定します。型は数値で整数で指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|1 |1地域
|2 |2地域
|3 |3地域
|4 |4地域
|5 |5地域
|6 |6地域
|7 |7地域
|8 |8地域
|===

==== typeキー

住宅タイプは次の表の値を指定します。型は文字列で指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|一般住宅 |住宅版
|行政庁認定住宅 |気候風土適応型住宅版
|事業主基準 |特定建築主基準版
|===

==== tatekata キー

住宅の建て方は次の表の値を指定します。型は文字列です。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|戸建住宅 |戸建住宅
|共同住宅 |共同住宅
|===

==== n_p キー

住宅の居住人数を次の表の値から指定します。型は文字列です。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|1人 |1人
|2人 |2人
|3人 |3人
|4人以上 |4人以上
|===

==== A_A キー

床面積の合計は小数で指定します。

==== A_MR キー

主たる居室の床面積は小数で指定します。

==== A_OR キー

その他の居室の床面積は小数で指定します。

==== sol_region キー

年間の日射地域区分は次の表の値を指定します。型は数値で整数で指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|1 |A1区分（年間の日射量が特に少ない地域）
|2 |A2区分（年間の日射量が少ない地域）
|3 |A3区分（年間の日射量が中程度の地域）
|4 |A4区分（年間の日射量が多い地域）
|5 |A5区分（年間の日射量が特に多い地域）
|===

==== reference キー ※ver3削除

基準値計算年度を表す<<基準値計算年度オブジェクト>>です。

==== ENV キー

外皮性能を表す<<外皮オブジェクト>>です。

==== NV_MRキー

主たる居室の自然風の利用は次の表の値を指定します。型は数値で整数で指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|0 |評価しない、または利用しない
|5 |利用する（換気回数5回/h相当以上）
|20 |利用する（換気回数20回/h相当以上）
|===

==== NV_OR キー

その他の居室の自然風の利用は次の表の値を指定します。型は数値で整数で指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|0 |評価しない、または利用しない
|5 |利用する（換気回数5回/h相当以上）
|20 |利用する（換気回数20回/h相当以上）
|===

==== TS キー

蓄熱の利用は次の表の値を指定します。型はbooleanで指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|false |評価しない、または利用しない
|true |利用する
|===

==== r_A_ufvnt キー

外気が経由する床下の面積の割合は小数で指定します。

==== underfloor_insulation キー

床下空間の断熱は次の表の値を指定します。型はbooleanで指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|false |断熱区画外
|true |断熱区画内
|===

==== mode_H キー

暖房方式は次の表の値を指定します。型は文字列で指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|住戸全体を連続的に暖房する方式 |住戸全体を連続的に暖房する方式

|居室のみを暖房する方式でかつ主たる居室とその他の居室ともに温水暖房を設置する場合に該当しない場合
|居室のみを暖房する方式でかつ主たる居室とその他の居室ともに温水暖房を設置する場合に該当しない場合

|設置しない |暖房設備機器等を設置しない場合
|===

==== H_A キー

住戸全体の暖房設備機器を表す<<住戸全体の暖房設備オブジェクト>>です。

==== H_MR キー

主たる居室の暖房設備機器または放熱器を表す<<主たる居室の暖房設備オブジェクト>>です。

==== H_OR キー

その他の居室の暖房設備機器または放熱器を表す<<その他の居室の暖房設備オブジェクト>>です。


==== H_HS キー

温水暖房機を表す<<温水暖房機オブジェクト>>です。

==== mode_C キー

冷房方式は次の表の値を指定します。型は文字列で指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|住戸全体を連続的に冷房する方式 |住戸全体を連続的に冷房する方式
|居室のみを冷房する方式 |居室のみを冷房する方式
|設置しない |冷房設備機器等を設置しない場合
|===

==== C_A キー

住戸全体の冷房設備機器を表す<<住戸全体の冷房設備オブジェクト>>です。

==== C_MR キー

主たる居室の冷房設備機器を表す<<主たる居室の冷房設備オブジェクト>>です。

==== C_OR キー

その他の居室の冷房設備機器を表す<<その他の居室の冷房設備オブジェクト>>です。

==== HW キー

給湯設備を表す<<給湯設備オブジェクト>>です。

==== V キー

換気設備を表す<<換気設備オブジェクト>>です。

==== HEX キー

熱交換型換気設備を表す<<熱交換型換気設備オブジェクト>>です。

==== L キー

照明設備を表す<<照明設備オブジェクト>>です。

==== SHC キー

太陽熱利用を表す<<太陽熱利用オブジェクト>>です。

==== PV キー

太陽光発電設備を表す<<太陽光発電設備の配列>>です。

==== CG キー

コージェネレーション設備を表す<<コージェネレーション設備オブジェクト>>です。

=== ルートオブジェクトの例

----
{
   "region":6,
   "type":"一般住宅",
   "reference":{
      "reference_year":null
   },
   "tatekata":"戸建住宅",
   "sol_region":null,
   "n_p": "4人以上",
   "A_A":120.08,
   "A_MR":29.81,
   "A_OR":51.34,
   "ENV":{
      "method":"当該住宅の外皮面積の合計を用いて評価する",
      "A_env":307.51,
      "A_A":120.08,
      "U_A":0.87,
      "eta_A_H":4.3,
      "eta_A_C":2.8
   },
   "NV_MR":0,
   "NV_OR":0,
   "TS":false,
   "r_A_ufvnt":null,
   "underfloor_insulation":null,
   "mode_H":"居室のみを暖房する方式でかつ主たる居室とその他の居室ともに温水暖房を設置する場合に該当しない場合",
   "mode_C":"居室のみを冷房する方式",
   "H_A":null,
   "H_MR":{
      "type":"ルームエアコンディショナー",
      "mode":"間歇",
      "e_class":null,
      "dualcompressor":false
   },
   "H_OR":{
      "type":"ルームエアコンディショナー",
      "mode":"間歇",
      "e_class":null,
      "dualcompressor":false
   },
   "H_HS":null,
   "C_A":null,
   "C_MR":{
      "type":"ルームエアコンディショナー",
      "e_class":null,
      "dualcompressor":false
   },
   "C_OR":{
      "type":"ルームエアコンディショナー",
      "e_class":null,
      "dualcompressor":false
   },
   "HW":{
      "has_bath":true,
      "hw_type":"コージェネレーションを使用する",
      "hybrid_category":null,
      "e_rtd":null,
      "e_dash_rtd":null,
      "kitchen_watersaving_A":false,
      "kitchen_watersaving_C":false,
      "shower_watersaving_A":false,
      "shower_watersaving_B":false,
      "washbowl_watersaving_C":false,
      "bath_insulation":false,
      "bath_function":"ふろ給湯機(追焚あり)",
      "pipe_diameter":"上記以外"
   },
   "V":{
      "type":"ダクト式第二種換気設備又はダクト式第三種換気設備",
      "input":"評価しない",
      "N":0.5
   },
   "HEX":null,
   "L":{
      "has_OR":true,
      "has_NO":true,
      "A_OR":51.34,
      "MR_installed":"設置しない",
      "OR_installed":"設置しない",
      "NO_installed":"設置しない"
   },
   "SHC":null,
   "PV":null,
   "CG":{
      "package_id":3,
      "reverse":true,
      "exhaust":false,
      "exhaust_priority":"ND",
      "type_BB_HWH":"G_EJ",
      "r_DHW_gen_PU_d":0.8942,
      "r_HWH_gen_PU_d":null,
      "P_TU_aux_HWH":null,
      "PU_type":"熱主",
      "param_E_E_gen_PU_Evt_d":{
         "a_PU":0.8546,
         "a_DHW":0.0,
         "a_HWH":0.0,
         "b":-5.5854,
         "c":0.8511
      },
      "param_E_F_PU_HVt_d":{
         "a_DHW":1.0,
         "a_HWH":0.0
      },
      "param_r_H_gen_PU_HVt_d":{
         "a_DHW":0.0177,
         "a_HWH":0.0,
         "b":0.6022
      },
      "param_e_E_PU_d":{
         "a_PU":0.0,
         "a_DHW":0.00040199999999999996,
         "a_HWH":0.0,
         "b":0.3111,
         "e_E_PU_d_max":0.3396,
         "e_E_PU_d_min":0.2959
      },
      "param_e_H_PU_d":{
         "a_PU":0.003019,
         "a_DHW":0.0,
         "a_HWH":0.0,
         "b":0.2496,
         "e_H_PU_d_max":0.4059,
         "e_H_PU_d_min":0.3351
      },
      "P_rtd_PU":750.0,
      "P_TU_aux_DHW":11.2
   },
   "AP": {
      "mode": "個々の家電機器を計算する方法",
      "JISYearOfRefrigerator": "2006",
      "RefrigeratorPower": 330,
      "ExistsTV": true,
      "RatedViewTVPower": 125,
      "RatedStandbyTVPower": 0.15,
      "ExistsToiletSeatHeater": false,
      "RatedLaundryPower": 51,
      "ExistsKettle": false,
      "RatedKettlePower": 1160
   }
}
----


<<<

include::basic.adoc[]

<<<

include::envelope.adoc[]

<<<

include::heating.adoc[]

<<<

include::cooling.adoc[]

<<<

include::ventilation.adoc[]

<<<

include::hotwater.adoc[]

<<<

include::lighting.adoc[]

<<<

include::photovoltaic.adoc[]

<<<

include::solarheating.adoc[]

<<<

include::cogeneration.adoc[]

<<<

include::appliance.adoc[]

<<<

include::subelement.adoc[]
