[[太陽熱利用オブジェクト]]
== 太陽熱利用オブジェクト

=== 概要

太陽熱利用を表すオブジェクトです。次の表のキーから構成されます。

[width="100%",cols="30%, 20%, 50%",options="header",]
|===
|キー |型 |意味
|type |文字列 |太陽熱利用設備の種類

|ls_type |文字列 |液体集熱式太陽熱利用設備の種類

|A_sp |数値 |面積

|P_alpha_sp |数値 |液体集熱式集熱部の設置方位角

|P_beta_sp |数値 |集熱部の設置傾斜角

|W_tnk_ss |数値 |液体集熱式貯湯タンクの容量

|P_alpha |数値 |空気集熱式集熱部の方位角

|fan_sso |真偽値 |空気搬送ファンの自立運転用太陽光発電装置の採用

|fan_type |文字列 |空気搬送ファンの種別

|hotwater_use |真偽値 |集熱した熱の給湯への利用

|pump_sso |真偽値 |循環ポンプの自立運転用太陽光発電装置の採用

|W_tnk_ass |数値 |空気集熱式給湯部のタンク容量

|V_fan_P0 |数値
|空気搬送ファンの送風機特性曲線において機外静圧をゼロとした時の空気搬送ファンの風量

|A_col |面積の配列 |集熱器群の面積の配列

|P_beta |傾斜角の配列 |集熱器群の傾斜角の配列

|d0 |切片の配列 |集熱器の集熱効率特性線図一次近似式の切片の配列

|d1 |傾きの配列 |集熱器の集熱効率特性線図一次近似式の傾きの配列

|m_fan_test |質量流量の配列
|集熱器の集熱性能試験時における単位面積当たりの空気の質量流量の配列

|supply_target |文字列 |集熱後の空気を供給する空間

|r_A_ufvnt_ass　|数値 |集熱後の空気を供給する床下の面積の割合

|ufv_insulation |真偽値 |床下空間の断熱
|===

=== キー

==== type キー

太陽熱利用設備の種類は次の表の値を指定します。型は文字列で指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|液体集熱式 |液体集熱式
|空気集熱式 |空気集熱式
|===

==== ls_type キー

液体集熱式太陽熱利用設備の種類は次の表の値を指定します。型は文字列で指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|太陽熱温水器 |太陽熱温水器
|ソーラーシステム |ソーラーシステム
|===

==== A_sp キー

面積は小数で指定します。

==== P_alpha_sp キー

液体集熱式集熱部の設置方位角は小数で指定します。

==== P_beta_sp キー

集熱部の設置傾斜角は小数で指定します。

==== W_tnk_ss キー

液体集熱式貯湯タンクの容量は整数で指定します。

==== P_alpha キー

空気集熱式集熱部の方位角は小数で指定します。

==== fan_sso キー

空気搬送ファンの自立運転用太陽光発電装置の採用は次の表の値を指定します。型はbooleanで指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|false |採用しない
|true |採用する
|===

==== fan_type キー

空気搬送ファンの種別は次の表の値を指定します。型は文字列で指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|DC |DCファン
|AC |ACファン
|===

==== hotwater_use キー

集熱した熱の給湯への利用は次の表の値を指定します。型はbooleanで指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|false |利用しない
|true |利用する
|===

==== pump_ssoキー

循環ポンプの自立運転用太陽光発電装置の採用は次の表の値を指定します。型はbooleanで指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|false |採用しない
|true |採用する
|===

==== W_tnk_ass キー

空気集熱式給湯部のタンク容量量は整数で指定します。

==== V_fan_P0 キー

空気搬送ファンの送風機特性曲線において機外静圧をゼロとした時の空気搬送ファンの風量は小数で指定します。

==== A_col キー

集熱器群の面積の配列は集熱器群の面数分の要素を持った配列です。要素は小数で指定します。

==== P_beta キー

集熱器群の傾斜角の配列は集熱器群の面数分の要素を持った配列です。要素は小数で指定します。

==== d0 キー

集熱器の集熱効率特性線図一次近似式の切片の配列は集熱器群の面数分の要素を持った配列です。要素は小数で指定します。

==== d1 キー

集熱器の集熱効率特性線図一次近似式の傾きの配列集熱器群の面数分の要素を持った配列です。要素は小数で指定します。

==== m_fan_test キー

集熱器の集熱性能試験時における単位面積当たりの空気の質量流量の配列は集熱器群の面数分の要素を持った配列です。要素は小数で指定します。

==== supply_target キー

集熱後の空気を供給する空間は次の表の値を指定します。型は文字列で指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|床下 |床下空間
|居室 |床下空間以外の室内空間
|===

==== r_A_ufvnt_ass キー

集熱後の空気を供給する床下の面積の割合は小数で指定します。

==== ufv_insulation キー

床下空間の断熱は次の表の値を指定します。型はbooleanで指定します。

[width="100%",cols="30%,70%",options="header",]
|===
|値 |意味
|false |断熱区画外
|True |断熱区画内
|===

=== 太陽熱利用オブジェクトの例

液体集熱式太陽熱利用設備を設置する場合の例

----
"SHC":{
  "type":"液体集熱式",
  "ls_type":"太陽熱温水器",
  "A_sp":0.425,
  "P_alpha_sp":6.283185307179586,
  "P_beta_sp":0.5235987755982988,
  "W_tnk_ss":100
 }
----

空気集熱式太陽熱利用設備を設置する場合の例

----
"SHC":{
  "type":"空気集熱式",
  "P_alpha":6.283185307179586,
  "fan_sso":false,
  "fan_type":"AC",
  "hotwater_use":false,
  "pump_sso":null,
  "W_tnk_ass":null,
  "V_fan_P0":0.1,
  "A_col":(0.5,
    0.5,
    0.5,
    0.5),
  "P_beta":[0.5235987755982988,
    0.5235987755982988,
    0.5235987755982988,
    0.5235987755982988],
  "d0":[0.1,
    0.1,
    0.1,
    0.1],
  "d1":[2.0,
    2.0,
    2.0,
    2.0],
  "m_fan_test":[0.0107,
    0.0107,
    0.0107,
    0.0107],
  "supply_target":"床下",
  "r_A_ufvnt_ass":0.5,
  "ufv_insulation":false
}
----
